  ########## Installing Domain Manager #############
  - name: Installing Domain Manager
    shell:
      cmd: ./installDomainManager.sh -install installDomainManager.properties
      chdir: "{{ install_dir }}/{{ untar_dir }}/bin" #/home/padtec/ansible_abhishek/OTS12_EKINMS_V1.1.16/bin
    args:
      executable: /bin/bash
    register: cmd_output
  - debug:
     msg: "{{ cmd_output.stdout_lines }}"

