  - name: Updating installPNMS.properties file
    lineinfile:
     path: "{{ installDir }}/{{ untar_dir }}/bin/installPNMS.properties"
     regexp: '^INSTALL_PADNMS_DIR='
     line: INSTALL_PADNMS_DIR={{ installDir }}/{{ untar_dir }}/etc

  - name: Updating installPNMS.properties file
    lineinfile:
      path: "{{ installDir }}/{{ untar_dir }}/bin/installPNMS.properties"
      regexp: '^INSTALL_PNMS_DIR='
      line: INSTALL_PNMS_DIR={{ installDir }}/{{ untar_dir }}/pnmsinstall

  - name: Updating installPNMS.properties file
    lineinfile:
      path: "{{ installDir }}/{{ untar_dir }}/bin/installPNMS.properties"
      regexp: '^INSTALL_MED_DIR='
      line: INSTALL_MED_DIR={{ installDir }}/{{ untar_dir }}/medinstall

