  ########## Copying files remotely #################
  - name: Copy start script from local to remote
    copy:
      src: /etc/ansible/abhishek/startInNonHaMode_nonHA.sh
      dest: "{{ installDir }}/{{ untar_dir }}/bin" #/home/padtec/ansible_abhishek/OTS12_EKINMS_V1.1.16/bin

  - name: Copy start script from local to remote
    copy:
      src: /etc/ansible/abhishek/startInNonHaMode_onlyPNMS.sh
      dest: "{{ installDir }}/{{ untar_dir }}/bin" #/home/padtec/ansible_abhishek/OTS12_EKINMS_V1.1.16/bin

  ########## Changing file ownership remotely #################
  - name: Changing start scripts ownership
    file:
      path: "{{ installDir }}/{{ untar_dir }}/bin/startInNonHaMode_nonHA.sh"
      mode: '0755'

  - name: Changing start scripts ownership
    file:
      path: "{{ installDir }}/{{ untar_dir }}/bin/startInNonHaMode_onlyPNMS.sh"
      mode: '0755'


