---
# This playbook runs a basic DF command.

- hosts: NMS_1
  #remote_user: root
  vars:
       isHA: "{{ lookup('ini', 'isHA section=general file=config.ini') }}"
       install_dir: "{{ lookup('ini', 'installDir section=general file=config.ini') }}"
       build_name: "{{ lookup('ini', 'buildName section=general file=config.ini') }}"
       nms_ip_1: "{{ lookup('ini', 'nms_ip_1 section=NMS_1 file=config.ini') }}"
       med_ip_1: "{{ lookup('ini', 'med_ip_1 section=MED_1 file=config.ini') }}"
       ncs_ip_1: "{{ lookup('ini', 'ncs_ip_1 section=NCS_1 file=config.ini') }}"
  tasks:
          #  - name: Reading variables from config file
    #vars:
    #  gen_lst:  
    #set_fact:
            # gen_lst: "{{ gen_lst }}, {{ item }}"
            #with_ini:
            #- '.* section=general file=config.ini re=True'
        #  - debug:
        #msg: "{{ gen_lst }}"
        #  - meta: end_play
  - debug:
      msg: 
       - "isHA is set to :  {{ isHA | type_debug}}"
       - "Installation Directory:  {{ install_dir }}"
       - "Build Name:  {{ build_name }}"
         #- meta: end_play
  - name: Unarchive the tar.gz
    unarchive:
     src: "{{ install_dir }}/{{ build_name }}"
     dest: "{{ install_dir }}"
     remote_src: yes
     list_files: yes
    register: archive_contents
  - set_fact:
      untar_dir: "{{ archive_contents.files[0].split('/')[0] }}"
      #- debug: 
      #msg : "{{ archive_contents.files[0] }}"
  - name: Updating installPNMS.properties file
    lineinfile:
      path: "{{ install_dir }}/{{ untar_dir }}/bin/installPNMS.properties"
      regexp: '^PNMS_IP='
      line: PNMS_IP={{ nms_ip_1 }}
  - lineinfile:
      path: "{{ install_dir }}/{{ untar_dir }}/bin/installPNMS.properties"
      regexp: '^INSTALL_PADNMS_DIR='
      line: INSTALL_PADNMS_DIR={{ install_dir }}/{{ untar_dir }}/etc
  - lineinfile:
      path: "{{ install_dir }}/{{ untar_dir }}/bin/installPNMS.properties"
      regexp: '^INSTALL_PNMS_DIR='
      line: INSTALL_PNMS_DIR={{ install_dir }}/{{ untar_dir }}/pnmsinstall
  - lineinfile:
      path: "{{ install_dir }}/{{ untar_dir }}/bin/installPNMS.properties"
      regexp: '^INSTALL_MED_DIR='
      line: INSTALL_MED_DIR={{ install_dir }}/{{ untar_dir }}/medinstall
  - lineinfile:
      path: "{{ install_dir }}/{{ untar_dir }}/bin/installPNMS.properties"
      regexp: '^BUILD_NAME='
      line: BUILD_NAME={{ untar_dir }}
  - lineinfile:
      path: "{{ install_dir }}/{{ untar_dir }}/bin/installPNMS.properties"
      regexp: '^VIRTUAL_IP='
      line: VIRTUAL_IP=127.0.0.1
    when: (isHA | int)==0

  - name: Updating installMediator.properties file
    lineinfile:
      path: "{{ install_dir }}/{{ untar_dir }}/bin/installMediator.properties"
      regexp: '^INSTALL_MED_DIR='
      line: INSTALL_MED_DIR={{ install_dir }}/{{ untar_dir }}/medinstall



  - name: Updating installDomainManager.properties file
    lineinfile:
      path: "{{ install_dir }}/installDomainManager.properties"
      regexp: '^NCS_IP='
      line: NCS_IP={{ ncs_ip_1 }}

  - name: Updating installTopology.properties file
    lineinfile:
      path: "{{ install_dir }}/installTopology.properties"
      regexp: '^NCS_IP='
      line: NCS_IP={{ ncs_ip_1 }}

