  - name: Updating installNodeManager.properties file
    lineinfile:
      path: "{{ install_dir }}/{{ untar_dir }}/bin/installNodeManager.properties"
      regexp: '^INSTALL_NODEMANAGER_DIR='
      line: INSTALL_NODEMANAGER_DIR={{ install_dir }}/{{ untar_dir }}/installnodemanager

